# Generated by Django 2.2.2 on 2020-11-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='menus',
            field=models.ManyToManyField(blank=True, help_text='可以打开那些菜单', to='rbac.Menus', verbose_name='拥有的菜单权限'),
        ),
    ]
