# Generated by Django 2.2.2 on 2020-12-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20201201_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='icon',
            field=models.CharField(default='111', help_text='指定显示的icon图标', max_length=32, verbose_name='图标'),
        ),
    ]
