# Generated by Django 2.2.2 on 2020-12-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20201204_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='method_type',
            new_name='method',
        ),
    ]
