# Generated by Django 2.2.2 on 2020-12-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_joined',
            new_name='create_time',
        ),
    ]
