# Generated by Django 2.2.2 on 2020-11-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='菜单名称')),
                ('url', models.CharField(max_length=128, unique=True, verbose_name='含正则的URL')),
                ('pid', models.IntegerField(blank=True, help_text='为0则是一级菜单,指定id则是指定id的二级菜单', null=True, verbose_name='是否为主菜单')),
            ],
            options={
                'verbose_name': '菜单表',
                'verbose_name_plural': '菜单表',
                'db_table': 'rbac_menus',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='名称')),
                ('url', models.CharField(max_length=128, unique=True, verbose_name='含正则的URL')),
                ('method_type', models.CharField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT'), (4, 'PATCH'), (4, 'DELETE')], default=1, help_text='请求的类型', max_length=1, verbose_name='请求类型')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('pid', models.IntegerField(blank=True, help_text='0为权限分类指定ID则属于二级', null=True, verbose_name='是否为分类')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
                'db_table': 'rbac_permissions',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='角色名称')),
                ('slug', models.CharField(max_length=64, unique=True, verbose_name='标识')),
                ('remarks', models.TextField(blank=True, default=None, null=True, verbose_name='备注')),
                ('menus', models.ManyToManyField(help_text='可以打开那些菜单', to='rbac.Menus', verbose_name='拥有的菜单权限')),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.Permissions', verbose_name='拥有的所有权限')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'db_table': '_rbac_roles',
            },
        ),
    ]
