# Generated by Django 2.2.2 on 2020-12-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20201204_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='method_type',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', help_text='请求的类型', max_length=10, verbose_name='请求类型'),
        ),
    ]
